### ISSUE TITLE
atari exploration problem

### ISSUE THREAD

**Issue by hlsafin** [facebookresearch/e3b#3]
I have tried using several different hyperparameters, but I have been unable to get my model to converge on some difficult exploration games in Atari(Gravitar and H.E.R.O), even after 5 billion timesteps. Can you suggest some effective hyperparameters for these games or provide an explanation for why you think my model is not converging? 

Here are the hyperparameters i've tested : intweight (3e-07,2.0), reward_norm (all,intr,ext). I tried both extremes, it seems like the inverse dynamic loss stays around the same value and doesn't decrease.

**Comment by mbhenaff** [comment]
It does sound odd that the inverse dynamics loss is not decreasing - for MiniHack the IDM loss decreases nicely (see attached figure). I think making sure the IDM loss decreases properly would be a first sanity check. You could try tuning the entropy cost of the policy - if this is too high, then the policy might output a distribution close to uniform over actions in which case there is not much signal for the IDM to pick up on. Specifically you could try decreasing the `entropy_cost` parameter from 0.005 to 0.001, 0.0005, 0.0001. Also you could plot the entropy of the policy and check that it is lower than that of a uniform distribution, which is `-log(num_actions)`. 




![Screen Shot 2022-12-20 at 1 35 48 PM](https://user-images.githubusercontent.com/5530315/208741008-2d549ec1-32b3-483f-88bb-262f6af8e7b0.png)

**Comment by mbhenaff** [comment]
Also, when tuning hyperparameters I would probably stick with intrinsic reward normalization alone (i.e. `reward_norm='intr'`) or none at all. If you have sparse reward then extrinsic alone will not be very helpful. I think it's more important to tune the intrinsic reward coefficient, like `10.0, 3.0, 1.0, 0.3, 0.1` or something when using intrinsic reward normalization. When using none, the range of optimal values can vary a lot more.

**Comment by hlsafin** [comment]
reward = norm(intr) + (`intweight`)*norm(extr) .
Do you think this norm might be better? Also, the majority of the games like Gravitar and H.E.R.O both have dense rewards but to get high score you need further exploration and not only focus on intermediate rewards. I'll try again with a different `entropy_cost` and see if this makes a difference. I don't believe actions are uniform because it achieves relatively high score, however, it's either not exploring or maybe the exploration process is very slow. The inverse loss starts at 150, decreases to 90, and hovers around 90 for the duration of training. I will do further testing and training.

**Comment by mbhenaff** [comment]
You could try that, maybe with a slight modification as follows: reward = (intweight)*norm(intr) + norm(extr). Note that you would need two separate reward normalizers, one for the intrinsic and one for the extrinsic rewards. 

If the inverse dynamics loss goes from 150 to 90 that suggests it is learning something. 

Is the issue that the agent isn't learning anything, or that it doesn't seem to improve over an agent trained with dense reward only? As a sanity check you could turn the intrinsic reward off (just set intweight=0) and check that the reward improves there. For Gravitar and Hero you should recover the performance of standard IMPALA (you may need to change the hyperparameters from the defaults though though since they might be different for MiniHack and Atari). 

Also, I think it might be harder to get improvements with E3B over IMPALA on dense reward games. You might have better luck on sparse reward games like Montezuma's Revenge. Getting it to work there would at least tell you that the hyperparameters are good.

**Comment by hlsafin** [comment]
Yeah, I tried e3b on Montezuma revenge with no ext rewards, and after 1 billion steps the reward was still 0.
