### ISSUE TITLE
Errors in mylevel.des

### ISSUE THREAD

**Issue by zhongdy15** [facebookresearch/e3b#5]
Hi there!

Firstly, I want to express my gratitude for sharing your code with the community. I've been able to successfully reproduce the E3B and obtain the expected results. However, I've encountered the following error during the environment setup and initialization process:

> mylevel.des: line 30, pos 0: Map too large at (25 x 22), max is (76 x 21) at "ENDMAP"
> mylevel.des: 1 errors detected for level "mylevel". No output created!

While the training ultimately produces the desired outcomes, I'm curious to understand the source of this error. It appears to be related to either the Minihack or Gym-Minigrid package. Could you provide some insights into the origin of this issue and its potential implications?

Thank you once again for your contribution, and I appreciate any assistance you can offer in resolving this matter.

**Comment by mbhenaff** [comment]
Hi, apologies for the late response. I believe this is due to Minigrid occasionally generating maps which are too large and exceed some limit in NetHack (for example, in that message the size is (25x22) but the limit on the dimensions is (76 x 21)). When this happens, the map is regenerated until one that fits is found. Hope this helps answer your question!
